version: '3'

services:
  api:
    build: ./flaskapi
    ports:
      - "8080:8080"
    volumes:
      - ./flaskapi:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=prefab-research-352802-3773376dfad4.json